version: "3"
services:
  api-server:
    container_name: urlshortener-springboot
    build:
      context: .
      dockerfile: api.Dockerfile
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysqlurldb:3306/urldb?allowPublicKeyRetrieval=true&useSSL=false
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=pa55w0rd
    ports:
      - "8080:8080"
    networks:
      - urlshortener-mysql-network
    depends_on:
      api-db:
        condition: service_healthy

  api-db:
    container_name: mysqlurldb
    build:
      context: .
      dockerfile: db.Dockerfile
    networks:
      - urlshortener-mysql-network
    environment:
      - MYSQL_ROOT_PASSWORD=pa55w0rd
      - MYSQL_DATABASE=urldb
      - MYSQL_USER=urlshortener
      - MYSQL_PASSWORD=123456
    ports:
      - '3306:3306'
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-ppa55w0rd"]
      interval: 5s
      timeout: 3s
      retries: 20

networks:
  urlshortener-mysql-network:
